# Generated by Django 4.0.4 on 2023-04-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
