# Generated by Django 4.0.4 on 2023-04-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
