# Generated by Django 4.0.4 on 2022-10-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['client']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='daily_calorie_consumption',
        ),
        migrations.RemoveField(
            model_name='task',
            name='daily_hours_fasted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='exercise_daily_calores_burned',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='weight',
        ),
        migrations.AddField(
            model_name='task',
            name='current_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='version_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.client'),
        ),
    ]
