# Generated by Django 4.0.4 on 2023-01-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_note_alter_task_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_product', models.CharField(max_length=250, null=True)),
                ('the_current_version', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
