# Generated by Django 4.0.4 on 2023-03-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='the_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
    ]
