# Generated by Django 4.0.4 on 2023-03-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_version_the_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='the_product',
            new_name='product_item',
        ),
    ]
