# Generated by Django 4.0.4 on 2023-03-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_the_product_version_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='product_item',
            new_name='the_product',
        ),
    ]
